apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  namespace: aconcert
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
        - name: gateway
          image: boom9387/gateway-service:latest
          ports:
            - containerPort: 8000
          envFrom:
            - secretRef:
                name: gateway-env
          env:
            - name: AUTH_SERVICE_URL
              value: http://auth-service:8000
            - name: EVENT_SERVICE_URL
              value: http://event-service:8000
            - name: LOCATION_SERVICE_URL
              value: http://location-service:8000
            - name: RESERVATION_SERVICE_URL
              value: http://reservation-service:8000
            - name: PAYMENT_SERVICE_URL
              value: http://payment-service:8000
            - name: NOTIFICATION_SERVICE_URL
              value: http://notification-service:8000
            - name: REALTIME_SERVICE_URL
              value: http://realtime-service:8000
---
apiVersion: v1
kind: Service
metadata:
  name: gateway
  namespace: aconcert
spec:
  selector:
    app: gateway
  ports:
    - port: 80
      targetPort: 8000
  type: LoadBalancer
